### ISSUE TITLE
Algorithms: TC using library API

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#100]
Implement Tc (triangle counting) aglorithm for directed graph.

> As a refererence see bfs and sssp algos' implementations

## Algo signature

a) ```void Tc(std::int32_t& ntrins, Ref<Matrix> &B, const Ref<Matrix> &A);```

b) ```void Tc(std::int32_t& ntrins, Ref<HostMatrix> &B, const Ref<HostMatrix> &A);```

Where:
- [out] ntris - number of triangles in the graph
- [out] B - matrix b with number of triangles per vertex
- [in] A - input adjacency matrix of directed graph with values of type int32_t, with `1` stored where has edge between i and j

## Files

- SplaAlgoTc.hpp - interface
- SplaAlgoTc.cpp - implementation in src
- TestAlgoTc.cpp - tests

## Tasks

- [ ] Implement signature for spla and naive cpu algo
- [ ] Implement spla algo
- [ ] Implement cpu algi
- [ ] Add tests for corretness/regression checks

## Also

Reference algo:
![image](https://user-images.githubusercontent.com/31863304/149131151-bb10662c-96a4-4664-be86-98200c9c3907.png)

More about desc:
![image](https://user-images.githubusercontent.com/31863304/149131945-4b9a33d1-9ae8-4555-b54d-bfe8b4a2261f.png)
