### ISSUE TITLE
Vector element-wise multiplication

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#102]
Implement vector-vector element-wise multiplication algorithm

## Description

w<mask> = accum(w, a `emult(op)` b)

- w - output vector
- a - input vector
- b - input vector
- mask - mask to filter result
- op - binary mult op of type `f: ta x tb -> tw`
- accum - binary op used to accum result of type `f: tw x tw -> tw`

## Signature

```cpp
RefPtr<ExpressionNode> MakeEWiseMult(const RefPtr<Vector> &w, 
                                     const RefPtr<Vector> &mask,
                                     const RefPtr<FunctionBinary> &accum,
                                     const RefPtr<FunctionBinary> &op,
                                     const RefPtr<Vector> &a,
                                     const RefPtr<Vector> &b,
                                     const RefPtr<Descriptor> &desc = nullptr);
```

## Tasks

- [ ] Expression node and signature
- [ ] Setup algo and params
- [ ] Implement blocked processing
- [ ] Implement coo algorithms
- [ ] Tests
- [ ] Handle no-values case
