### ISSUE TITLE
Matrix reduce to vector

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#106]
Implement matrix to vector reduce expression node.

## Signature

```c++
RefPtr<ExpressionNode> MakeReduce(const RefPtr<Vector> &w,
                                  const RefPtr<Matrix> &mask,
                                  const RefPtr<FunctionBinary> &accum,
                                  const RefPtr<FunctionBinary> &op,
                                  const RefPtr<Matrix> &a,
                                  const RefPtr<Descriptor> &desc = nullptr);
```

`w = accum(w, reduce(op) a)`

- w - vector to store result of type `t`
- mask - matrix mask to filter result
- op - function to reduce `f: t x t -> t`
- a - matrix to reduce of type `t`

## Expected behavior

`w[i] = accum(w[i], reduce(a[i,j] for j if (i,j) in mask, op))`

## Algo

- For each a.block[i,j] dispatch reduce and evaluate tmp_w[i] vectors
- Evaluate sum of tmp blocks: w = sum(w.block[i], tmp_w[i] ... , op)

## Tasks

- [ ] Setup signature
- [ ] Setup tests
- [ ] Setup coo algo `ParamsMatrixReduce`
- [ ] Implement coo algo
- [ ] Implement expr node
