### ISSUE TITLE
Matrix transpose

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#108]
Implement matrix transpose expression node.

## Signature

```c++
RefPtr<ExpressionNode> MakeTranspose(const RefPtr<Matrix> &w,
                                     const RefPtr<Matrix> &mask,
                                     const RefPtr<FunctionBinary> &accum,
                                     const RefPtr<Matrix> &a,
                                     const RefPtr<Descriptor> &desc = nullptr);
```

`w<mask> = accum(w, a^T)`

- w - matrix store result of type `t`
- mask - matrix mask to filter result
- accum - function to accum result `f: t x t -> t`
- a - matrix to transpose of type `t`

## Expected behavior

`w[i, j] = accum(w[i, j], a[j, i]) for (i,j) in mask`

## Algo

- transpose each input block
- accum results

## Tasks

- [ ] Setup signature
- [ ] Setup tests
- [ ] Setup coo algo `ParamsTranspose`
- [ ] Implement coo algo
- [ ] Implement expr node
