### ISSUE TITLE
Matrix reduce to scalar

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#111]
Implement matrix to scalar reduce expression node.

## Signature

```c++
RefPtr<ExpressionNode> MakeReduceScalar(const RefPtr<Scalar> &w,
                                        const RefPtr<Matrix> &mask,
                                        const RefPtr<FunctionBinary> &accum,
                                        const RefPtr<FunctionBinary> &op,
                                        const RefPtr<Matrix> &a,
                                        const RefPtr<Descriptor> &desc = nullptr);
```

`w = accum(w, reduce(op) a)`

- w - scalar to store result of type `t`
- mask - matrix mask to filter input
- op - function to reduce `f: t x t -> t`
- a - matrix to reduce of type `t`
- desc can have Complement flag (note!)

## Expected behavior

`w = accum(w, reduce(a[i,j] for (i,j) if (i,j) in mask, op))`

## Algo

- For each a.block[i,j] filter with mask and dispatch reduce and evaluate tmp_w[i,j] scalars
- Pack scalars into a matrix(vector) block
- Call reduce to reduce this tnp block to scalar w'
- If need apply accum, w = accum(w, w') else w = w'

## Tasks

- [ ] Setup signature
- [ ] Setup tests
- [ ] Setup coo algo `ParamsMatrixReduceScalar`
- [ ] Implement coo algo
- [ ] Implement expr node
- [ ] In no-values is not supported - cannot reduce to void scalar (check, that scalar has type with byteSize > 0)
