### ISSUE TITLE
Vector-vector ewiseadd

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#54]
Implement vector-vector element-wise addition expression node.

## Exprected behavior

`w<mask> = a ewiseadd(op) b`

Where:

- w - vector where to store result
- a - input a vector 
- b - input b vector 
- op - user defined element wise add
- mask - vector (used only indices), which defines, which values of the result to store. If mask null, the whole result is saved. 

## Tasks

- [x] Add node type `VectorVectorEWiseAdd` (note about ToStr method)
- [x] Add expression `MakeEWiseAdd(vector w, vector mask, vector a, vector b, functionbinary op, desc d)` function for node creation
- [x] Add expression node processor 
- [x] Implement opeartion for blocked storage
- [x] Add Algortihm impl for COO vector blocks ewise add
