### ISSUE TITLE
Matrix-matrix ewiseadd

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#55]
Implement matrix-matrix element-wise addition expression node.

## Exprected behavior

`w<mask> = a ewiseadd(op) b`

Where:

- w - matrix where to store result
- a - input a matrix
- b - input b matrix
- op - user defined element wise add
- mask - matrix (used only indices), which defines, which values of the result to store. If mask null, the whole result is saved. More specifically, `tmp = a ewiseadd b, output[i, j] = tmp[i, j] for i, j in mask`, where existing `ouput` values discarded.

## Research

- [x] Investigate cusp solution [link](
https://github.com/cusplibrary/cusplibrary/blob/develop/cusp/system/detail/generic/elementwise.inl)
- [x] Decide how to integrate masks
- [x] Decide how to handle arbitrary values

## Tasks

- [x] Add node type `MatrixMatrixEWiseAdd` (note about ToStr method)
- [x] Add expression `MakeEWiseAdd(matrix w, matrix mask, matrix a, matrix b, functionbinary op, desc d)` function for node creation
- [x] Add expression node processor 
- [x] Implement opeartion for blocked storage
- [x] Add Algortihm impl for COO matrix blocks ewise add
