### ISSUE TITLE
Matrix-matrix multiplication

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#79]
Implement matrix-matrix multiplication expression node.

## Expected behavior

`w<mask> = a mxm(mult, add) b`

Where:
- w - matrix where to store result of size `m x n`
- a - input a matrix of size `m x k`
- b - input b matrix of size `k x n`
- mult - binary funtion used to multiply elements of a and b of type `f: ta x tb -> tc`
- add - binary function used to sum results of multiplication of a and b values of type `f: tc x tc -> tc`
- mask - matrix (used only structure/indices), which defines, which values of the result to store. If mask null, the whole result is saved. More specifically, `tmp = a mxm b`, `output[i, j] = tmp[i, j] for i, j in mask`, where existing ouput values discarded.

## Signature

```cpp
RefPtr<ExpressionNode>
MakeMxM(const RefPtr<Matrix> &w,
        const RefPtr<Matrix> &mask,
        const RefPtr<FunctionBinary> &mult,
        const RefPtr<FunctionBinary> &add,
        const RefPtr<Matrix> &a,
        const RefPtr<Matrix> &b,
        const RefPtr<Descriptor> &desc);
```

## Algo structure

- Spawn tasks to calculate all blocked mxm products `tmp_ab[i,l,j] = a[i,l] x b[l, j]`
- Spawn tasks to sum all tmp results as `w[i,j] = sum(tmp_ab[i,l,j] for l in range 0..k) `

## Tasks

- [x] Add node type `MxM` 
- [x] Add expression signature
- [x] Add expression node processor
- [x] Implement operation for blocked storage using `algo` and `algo manager` abstraction
- [x] Add required tests 
- [x] Support masking 
- [ ] Handle case if `no values` in matrix
