### ISSUE TITLE
Matrix-matrix multiplication algo (coo format)

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#80]
Implement matrix-matrix multiplication algorithm to multiply two matrix blocks.

## Singnature

- w - matrix block to store result
- a - input matrix
- b - input matrix
- mult - binary function as `*`
- add - binary function as `+`
- ta - type of a elements
- tb - type of b elements
- tw - type of w elements

## Exprected result

`w[i, j] = a[i, 1] * b[1, j] + .... + a[i, k] * b[k, j]`

## Research

- cusp coo spgemm [link](https://github.com/cusplibrary/cusplibrary/blob/develop/cusp/system/cuda/detail/multiply/spgemm.h)
- look at multiply function
- look at coo spmm helper
- Maybe we need to split processing to parts as well, since this algo consumes so much memory, so it actually can exceed workspace limitations

## Tasks

- [x] Setup MxMCOO algorithms
- [x] Setup ParamsMxM structure
- [ ] Implement algorithm 
- [ ] Support masking
- [ ] Handle `no-values` case
