### ISSUE TITLE
Vector-matrix multiplication

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#82]
Implement vxm operation for vector-matrix multiplication.

## General

`w<mask>= v vxm(mult,add) m`

Where:
- w - output vector to store result `n`
- mask - vector mask `n`
- mult - binary multiply function `f: tv x tm -> tw`
- add - binary add function `f: tw x tw -> tw`
- v - input vector `m`
- m - input matrix `m x n`
- desc - operation descriptor

## Algorithm

- Spawn tasks to compute tmp_vm[i, j] = v[i] x m[i, j]
- Spawn tasks to reduce tmp results w[j] = sum(tmp_vm[i, j] for i in range 1..m)

## Tasks

- [x] Setup node processor
- [x] Add function signature
- [x] Implement blocked algorithm
- [x] Setup tests
- [x] Support masking 
- [x] Handle `no-values` case
