### ISSUE TITLE
Vector-matrix multiplication algo (coo format)

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#83]
Implement vector-matrix multiplication algorithm to multiply vector-matrix blocks.

## Expected result

`w[j] = v[1] * m[1, j] + ....  + v[m] * m[m, j]`

## Tasks

- [x] Setup VxMCOO algo
- [x] Setup ParamsVxM structure
- [x] Implement algorithm
- [x] Support masking
- [x] Handle no-values case
