### ISSUE TITLE
Inverse mask apply

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#85]
Support `!mask` apply to vector and matrix inoperations.

## Exprected behavior

For primitive v of size N:
- `v[!mask] = m <=> v[i] = m[i] for i in range(0, N) i not in mask`
 
## Tasks

- [ ] Add descriptor `MaskComplement` value
- [ ] Add complement mask algo
- [ ] Wrap mask apply for `bool complement` variant
- [ ] Use new mask apply in algorithms
