### ISSUE TITLE
Vector masked assign

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#86]
Implement vector masked scalar value assignment (handle coo case only).

## Signature

```c++
RefPtr<ExpressionNode> MakeAssign(const RefPtr<Vector> &w,
                                  const RefPtr<Vector> &mask,
                                  const RefPtr<Scalar> &s,
                                  const RefPtr<Descriptor> &desc = nullptr);
```

`w<mask> = s`
`w<!mask> = s`

- w - vector to store result
- mask - mask to select slots to assign (no mask, whole vector is filled)
- s - scalar value to assign
- mask or !mask is defined by desc (see #85)

## Expected behavior 

`w[i] = s for i in mask or w[i] = s for i in !mask (depends on descriptor)`

## Algo

For each block mask.b[i] of mask dispatch tf::Task to evaluatre w.b[i] = coo_assign(mask.b[i], s)

## Tasks

- [x] Setup signature
- [ ] Setup tests
- [x] Setup coo algo `ParamsVectorAssign`
- [ ] Implement coo algo
- [x] Implement expr node
- [ ] No values case
