### ISSUE TITLE
Vector reduce to scalar 

### ISSUE THREAD

**Issue by EgorOrachyov** [JetBrains-Research/spla#87]
Implement vector to scalar reduce expression node.

## Signature

```c++
RefPtr<ExpressionNode> MakeReduce(const RefPtr<Scalar> &s,
                                  const RefPtr<FunctionBinary> &op,
                                  const RefPtr<Vector> &v,
                                  const RefPtr<Descriptor> &desc = nullptr);
```

`s = reduce(op) v`

- s - scalar to store result of type `t`
- op - function to reduce `f: t x t -> t`
- v - vector to reduct of type `t`

## Expected behavior

`s = reduce(v[i] for i in range(v.nnz), reduce_op)`

## Algo

- For each v.block[i] dispatch reduce and evaluate tmp_s[i] scalars
- Reduce s = reduce(tmp_s[i] for in range v.nblocks, op)

## Tasks

- [ ] Setup signature
- [ ] Setup tests
- [ ] Setup coo algo `ParamsVectorReduce`
- [ ] Implement coo algo
- [ ] Implement expr node
